name: Grab release tag as an output

on:
  workflow_dispatch:
  
jobs:
  getReleaseTag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        
      - name: Get release tag via GH CLI
        id: get_tag
        run: |
          gh api https://api.github.com/repos/SullyDevSquad/gitflow-example/releases | jq -r '.[] | select(.draft == true) | .tag_name'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Echo output
        run: echo ${{ steps.get_tag.outputs.tagName }} 
